name: azat
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - blas=1.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - charset-normalizer=3.4.4
  - contourpy=1.3.2
  - cycler=0.12.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - freetype=2.14.1
  - freetype-py=2.3.0
  - icc_rt=2022.1.0
  - icu=75.1
  - kiwisolver=1.4.9
  - lcms2=2.17
  - lerc=4.0.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libdeflate=1.25
  - libexpat=2.7.1
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libglib=2.86.1
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.2
  - liblzma=5.8.1
  - libpng=1.6.50
  - libsqlite=3.51.0
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=21.1.5
  - matplotlib-base=3.10.6
  - mkl=2025.3.0
  - mkl-service=2.6.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.11
  - munkres=1.1.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openbabel=3.1.1
  - openjpeg=2.5.4
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.2
  - pcre2=10.46
  - pillow=12.0.0
  - pip=25.2
  - pixman=0.46.4
  - pthread-stubs=0.4
  - pycairo=1.29.0
  - pyparsing=3.2.5
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - qhull=2020.2
  - reportlab=4.4.4
  - rlpycairo=0.4.0
  - scipy=1.15.3
  - setuptools=80.9.0
  - six=1.17.0
  - tbb=2022.3.0
  - tk=8.6.13
  - tzdata=2025b
  - ucrt=10.0.26100.0
  - unicodedata2=17.0.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zlib-ng=2.2.5
  - zstd=1.5.7
  - pip:
      - colorama==0.4.6
      - dimorphite-dl==2.0.1
      - loguru==0.7.3
      - molvs==0.1.1
      - pyside6==6.9.2
      - pyside6-addons==6.9.2
      - pyside6-essentials==6.9.2
      - rdkit==2025.9.1
      - rdkit-pypi==2022.9.5
      - shiboken6==6.9.2
      - win32-setctime==1.2.0
